In [27]:
import cv2
import numpy as np
import os
import glob

In [28]:
#from google.colab.patches import cv2_imshow
# import cv2 as cv

In [29]:
CHECKERBOARD = (6, 9)

In [30]:
criteria = (cv2.TERM_CRITERIA_EPS +
            cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

In [31]:
threedpoints = []
twodpoints = []
objectp3d = np.zeros((1, CHECKERBOARD[0]
                      * CHECKERBOARD[1],
                      3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
                               0:CHECKERBOARD[1]].T.reshape(-1, 2)
#prev_img_shape = None
objectp3d *= 20
print(objectp3d)

[[[  0.   0.   0.]
  [ 20.   0.   0.]
  [ 40.   0.   0.]
  [ 60.   0.   0.]
  [ 80.   0.   0.]
  [100.   0.   0.]
  [  0.  20.   0.]
  [ 20.  20.   0.]
  [ 40.  20.   0.]
  [ 60.  20.   0.]
  [ 80.  20.   0.]
  [100.  20.   0.]
  [  0.  40.   0.]
  [ 20.  40.   0.]
  [ 40.  40.   0.]
  [ 60.  40.   0.]
  [ 80.  40.   0.]
  [100.  40.   0.]
  [  0.  60.   0.]
  [ 20.  60.   0.]
  [ 40.  60.   0.]
  [ 60.  60.   0.]
  [ 80.  60.   0.]
  [100.  60.   0.]
  [  0.  80.   0.]
  [ 20.  80.   0.]
  [ 40.  80.   0.]
  [ 60.  80.   0.]
  [ 80.  80.   0.]
  [100.  80.   0.]
  [  0. 100.   0.]
  [ 20. 100.   0.]
  [ 40. 100.   0.]
  [ 60. 100.   0.]
  [ 80. 100.   0.]
  [100. 100.   0.]
  [  0. 120.   0.]
  [ 20. 120.   0.]
  [ 40. 120.   0.]
  [ 60. 120.   0.]
  [ 80. 120.   0.]
  [100. 120.   0.]
  [  0. 140.   0.]
  [ 20. 140.   0.]
  [ 40. 140.   0.]
  [ 60. 140.   0.]
  [ 80. 140.   0.]
  [100. 140.   0.]
  [  0. 160.   0.]
  [ 20. 160.   0.]
  [ 40. 160.   0.]
  [ 60. 160.   0.]
  [ 80. 160.

In [32]:
folder_path = 'attachments'
images = glob.glob(os.path.join(folder_path, '*.jpg'))

In [33]:
for filename in images:
  
    # print(imagePath)
    image = cv2.imread(filename)
    grayColor = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    ret, corners = cv2.findChessboardCorners(
                    grayColor, CHECKERBOARD)
    print(ret)

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [34]:
if ret == True:
        threedpoints.append(objectp3d)
        corners2 = cv2.cornerSubPix(
            grayColor, corners, (11, 11), (-1, -1), criteria)
        twodpoints.append(corners2)
        image = cv2.drawChessboardCorners(image,
                                          CHECKERBOARD,
                                          corners2, ret)
        

In [35]:
cv2.imshow('image', image)
cv2.waitKey(0)

13

In [36]:
h, w = image.shape[:2]

ret, matrix, distortion, r_vecs, t_vecs = cv2.calibrateCamera(
    threedpoints, twodpoints, grayColor.shape[::-1], None, None)

print(" Camera matrix:")
print(matrix)

print("\n Distortion coefficient:")
print(distortion)

print("\n Rotation Vectors:")
print(r_vecs)

 Camera matrix:
[[3.47064189e+03 0.00000000e+00 7.20083890e+02]
 [0.00000000e+00 4.32731100e+03 3.16847916e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

 Distortion coefficient:
[[ 3.90858585e+00 -4.54111930e+02 -8.99012480e-02  9.74234371e-03
  -6.05987724e+00]]

 Rotation Vectors:
(array([[0.0406519 ],
       [0.9750166 ],
       [2.95451813]]),)
