In [11]:
import cv2
import numpy as np
import os
import glob


In [12]:
CHECKERBOARD = (6, 9)
criteria = (cv2.TERM_CRITERIA_EPS +
            cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
threedpoints = []
twodpoints = []
objectp3d = np.zeros((1, CHECKERBOARD[0]
                      * CHECKERBOARD[1],
                      3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
                               0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None


using laptop camera 

In [13]:
folder_path = 'attachments'
images = glob.glob(os.path.join(folder_path, '*.jpg'))

In [16]:
for filename in images:
    image = cv2.imread(filename)
    grayColor = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(
                    grayColor, CHECKERBOARD,
                    cv2.CALIB_CB_ADAPTIVE_THRESH
                    + cv2.CALIB_CB_FAST_CHECK +
                    cv2.CALIB_CB_NORMALIZE_IMAGE)
    print(ret,filename)
    if ret == True:
        threedpoints.append(objectp3d)
        corners2 = cv2.cornerSubPix(
            grayColor, corners, (11, 11), (-1, -1), criteria)
        twodpoints.append(corners2)
        image = cv2.drawChessboardCorners(image,
                                          CHECKERBOARD,
                                          corners2, ret)

True attachments/WIN_20240805_17_01_15_Pro.jpg
True attachments/WIN_20240805_17_01_41_Pro.jpg
True attachments/WIN_20240805_17_01_33_Pro.jpg
True attachments/WIN_20240805_17_01_40_Pro.jpg
True attachments/WIN_20240805_17_01_32_Pro.jpg
True attachments/WIN_20240805_17_01_30_Pro.jpg
True attachments/WIN_20240805_17_01_20_Pro.jpg
True attachments/WIN_20240805_17_01_29_Pro.jpg
True attachments/WIN_20240805_17_01_16_Pro.jpg
True attachments/WIN_20240805_17_01_38_Pro.jpg
True attachments/WIN_20240805_17_01_28_Pro.jpg
True attachments/WIN_20240805_17_01_35_Pro (2).jpg
True attachments/WIN_20240805_17_01_17_Pro.jpg
True attachments/WIN_20240805_17_01_21_Pro.jpg
True attachments/WIN_20240805_17_01_31_Pro.jpg
True attachments/WIN_20240805_17_01_43_Pro.jpg
True attachments/WIN_20240805_17_01_34_Pro.jpg
True attachments/WIN_20240805_17_01_24_Pro.jpg
True attachments/WIN_20240805_17_01_12_Pro.jpg
True attachments/WIN_20240805_17_01_19_Pro (2).jpg
True attachments/WIN_20240805_17_01_13_Pro.jpg
True 

In [18]:
h, w = image.shape[:2]

ret, matrix, distortion, r_vecs, t_vecs = cv2.calibrateCamera(
    threedpoints, twodpoints, grayColor.shape[::-1], None, None)

print(" Camera matrix:")
print(matrix)

print("\n Distortion coefficient:")
print(distortion)


 Camera matrix:
[[828.14368393   0.         623.07226705]
 [  0.         828.89319167 346.68051616]
 [  0.           0.           1.        ]]

 Distortion coefficient:
[[-0.03430804  0.5370896  -0.01778048  0.00350512 -1.702055  ]]


In [19]:

print("\n Rotation Vectors:")
print(r_vecs)


 Rotation Vectors:
(array([[0.05410936],
       [0.22640725],
       [3.130987  ]]), array([[1.67767501e-03],
       [3.27002701e-01],
       [3.02510658e+00]]), array([[0.02010002],
       [0.25411042],
       [3.1142806 ]]), array([[-0.07720138],
       [ 0.30877784],
       [ 3.12348201]]), array([[0.0110551 ],
       [0.24467763],
       [3.1161125 ]]), array([[-0.0586311 ],
       [-0.29403292],
       [-3.10499218]]), array([[ 0.03508206],
       [-0.34334694],
       [-3.08935335]]), array([[-0.08636502],
       [-0.23197694],
       [-3.10758017]]), array([[ 0.0047821 ],
       [-0.29208809],
       [-3.08939398]]), array([[-0.01826075],
       [ 0.2714827 ],
       [ 3.09207737]]), array([[ 0.11088541],
       [-0.38778442],
       [-3.07397992]]), array([[-0.01093543],
       [ 0.22033566],
       [ 3.09833168]]), array([[-0.02352211],
       [ 0.26332381],
       [ 3.11381814]]), array([[-0.073752  ],
       [ 0.31947495],
       [ 3.12783631]]), array([[0.04407581],
      